# -*- coding: utf-8 -*-
"""ML_Practical_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H32gO_PhqOscXiFskSI0GmC0I7BaPqWk

Logistic Regression
"""

from google.colab import drive
drive.mount("/content/drive")

#import necessary libaries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""1. Data Loading"""

# Load data
df = pd.read_csv("/content/drive/MyDrive/ML Practical/advertising.csv")
df.head()

"""2.Exploratory Data Analysis"""

print("Shape of dataset:",df.shape)#(rows,columns)

#Displays cloumns
print("\nColumn Names:")
print(df.columns)

#Displays info
print("\nDataset Information:")
df.info()

#Displays statistics
df.describe(exclude=object)

#Target Class distribution
print(df["Clicked on Ad"].value_counts())

df_corr=df.select_dtypes(include=['float64','int64']).corr()
plt.figure(figsize=(6,4))
sns.heatmap(df_corr, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap of Numerical Features')
plt.show()

"""3.Feature Selection And Data Splitting"""

X=df[["Daily Time Spent on Site","Daily Internet Usage"]]#Features
y=df["Clicked on Ad"]#Target
print("Features:")
print(X.head())
print('Target:')
print(y.head())

#Split Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y,test_size=0.20, random_state=42, stratify=y)
print("Training data:",X_train.shape)
print("Testing data:",X_test.shape)

#Init scaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_test_sc=pd.DataFrame(X_test_scaled)

X_test_sc.describe()

"""4.Model Training"""

#import model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
#Train model
model.fit(X_train_scaled, y_train)

#Predict labels
y_pred = model.predict(X_test_scaled)
# Predict Probabilities
y_probability = model.predict_proba(X_test_scaled)[:,1]
print("predicated classes:")
print(y_pred[:10])
print("\nPredicated Probabilities:")
print(y_probability[:10])

"""5.Model Evaluation"""

#Calculate accuracy
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

"""Confusion Matrix"""

#plot confusion matrix
plt.figure(figsize=(6,4))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d')
plt.title('Confusion Matrix')
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.show()

"""Classification Report"""

#Classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

from sklearn.metrics import precision_score
print('Precision',precision_score(y_test, y_pred))

"""ROC Curve and AUC"""

from sklearn.metrics import roc_auc_score, roc_curve
#Calculate FPR,TPR, thresholds
fpr, tpr, thresholds = roc_curve(y_test, y_probability)
#calculate AUC
auc = roc_auc_score(y_test, y_probability)
print("AUC:",auc)
plt.figure(figsize=(6,4))
plt.plot(fpr, tpr, label=f"Logistic Regression (AUC={auc:.2f})")
plt.plot([0, 1], [0, 1], linestyle="--", color="gray", label="Random Classifier")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Receive Operating Characteristic (ROC) Curve")
plt.legend()
plt.show()